### PR TITLE
Add Lift Void instance

### LINKED ISSUE #16: Backport Lift Void instance
`template-haskell-2.15` (GHC 8.8) will [debut](http://git.haskell.org/ghc.git/commit/47875bd4d79ca633b589e63e320aa5a5c631d096) a `Lift Void` instance. We should backport it in this library as well.

### PR DESCRIPTION
**Pull request by phadej**
Resolves #16 

EDIT: Latter commit supersedes #15

### CODE REVIEW

**Comment by phadej** [comment]
ping @RyanGlScott

**Comment by phadej** [comment]
@ekmett Ryan told that he doesn't have push access to this repository; and seems you are also the only one maintainer on Hackage. We (me and Ryan) can both take care of this.

**Comment by phadej** [comment]
ping @ekmett

**Comment by ekmett** [comment]
Mossed the precious notification as it came in while I was on vacation. Let me know if you are still stuck.

**Comment by phadej** [comment]
@ekmett if you could add Ryan (or me, or both) to http://hackage.haskell.org/package/void/maintainers/ that would be great

**Comment by phadej** [comment]
... and charset, for that matter: https://hackage.haskell.org/package/charset/maintainers

**Comment by phadej** [comment]
@ekmett ping

@RyanGlScott and I would like to bit a bullet soon, and release new majors `semigroups-0.19` and `void-0.8`, so we could sweep through the universe (making https://github.com/ekmett/lens/issues/845 even more mega than it is :)

**Comment by phadej** [comment]
@ekmett another ping. Herbert is very close to making `hashable-1.3` release, it would be nice to make `void` release promptly after; so we can update `hashable`, `semigroups` and `void` reverse dependencies in one pass.

**Comment by ekmett** [comment]
@phadej, @RyanGlScott: I've added you both here and on hackage to both `void` and `charset`.

**Comment by phadej** [comment]
@ekmett thanks!

**Pull request merged**
